
--13 List each order alongside the customer's name.
SELECT C.NAME, O.ORDER_ID FROM CUSTOMERS C INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID;

--14. List every customer, and their order id if they have one.
SELECT C.NAME, O.ORDER_ID FROM CUSTOMERS C LEFT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;

--15. Find customers who have never placed an order.
SELECT C.NAME, O.ORDER_ID FROM CUSTOMERS C LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID WHERE O.ORDER_ID IS NULL;

--16  List every employee with their manager's name.
SELECT E1.NAME AS "EMPLOYEE NAME", E2.NAME AS "MANAGER_NAME" FROM EMPLOYEES E1 INNER JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID;

--17 Reconcile two tables, showing rows that exist in only one of them.
SELECT C.CUSTOMER_ID, O.CUSTOMER_ID FROM CUSTOMERS C FULL OUTER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID WHERE O.CUSTOMER_ID IS NULL OR C.CUSTOMER_ID IS NULL;